version: "3" # composeファイルのバージョン
services:
    mysql:
        build: ./build/db/
        volumes:
            - ./docker/db/data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=reception
            - MYSQL_USER=gorugo
            - MYSQL_PASSWORD=gorupass
        platform: linux/amd64
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Tokyo
