openapi: 3.0.0
info:
  version: '1.0'
  title: Koyo-Back-Endpoint
  description: こうよう祭2023の受付システムのバックエンドエンドポイント
servers:
  - url: 'http://localhost:8080'
    description: ローカル
paths:
  '/users/{uid}':
    get:
      summary: ''
      description: ''
      operationId: get-users-uid
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/userdata'
        '400':
          $ref: '#/components/responses/error'
      servers:
        - url: 'http://localhost:8080'
          description: ローカル
    put:
      summary: ''
      operationId: put-users-uid
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                temperature_day1:
                  type: number
                  format: float
                temperature_day2:
                  type: number
                  format: float
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/error'
      servers:
        - url: 'http://localhost:8080'
          description: ローカル
components:
  requestBodies:
    temperature:
      description: temp
      content:
        application/json:
          schema:
            type: object
            properties:
              temperature_day1:
                type: number
                format: float
              temperature_day2:
                type: number
                format: float
  responses:
    userdata:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              uid:
                type: string
              attends_day1:
                type: boolean
              attends_day2:
                type: boolean
              temperature_day1:
                type: number
                format: float
              temperature_day2:
                type: number
                format: float
            required:
              - name
              - uid
              - attends_day1
              - attends_day2
    error:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
