swagger: "2.0"
info:
  title: KoyoFes_Back_API
  description: こうよう祭2023年度の受付システムのバックエンドAPI
  version: 1.0.0
schemes:
  - https
paths:
  /attend:
    get:
      summary: 受付可否
      parameters:
        - name: uid
          in: query
          description: UID
          required: true
          type: string
        - name: day
          in: query
          description: 何日目か
          required: true
          type: number
      responses:
        200:
          description: Success
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string
  /set_temperature:
    post:
      summary: 体温セット
      parameters:
        - name: UIDandBodytemp
          in: body
          description: UIDと体温
          required: true
          schema:
            type: object
            properties:
              uid:
                type: string
              day:
                type: number
                format: int
              bodytemp:
                type: number
                format: float
      responses:
        200:
          description: Success
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string